services:
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - kia-network

  #adminer:
   # image: adminer:5.0.2
   # container_name: adminer
   # restart: always
   # ports:
   #   - "8082:8080"
   # depends_on:
   #   - db
   # networks:
   #   - web-network

  backend:
    build: ./Finauto-Back-End
    container_name: backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NODE_ENV: staging
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kia-network

  front-admin:
    build: ./Finauto-Admin
    container_name: front-admin
   # environment:
   #   VITE_API_URL: https://api.finautointernational.com
    expose:
    #ports:
      - "8081:80"
    networks:
      - kia-network

  front-cliente:
    build: ./Finauto-Cliente
    container_name: front-cliente
    #environment:
    #  VITE_API_URL: https://api.finautointernational.com
    expose:
    #ports:
      - "8080:80"
    networks:
      - kia-network

  #nginx-proxy-manager:
  #  image: 'jc21/nginx-proxy-manager:latest'
  #  container_name: nginx-proxy-manager
  #  restart: always
  #  ports:
  #    - '80:80'      # HTTP
  #    - '81:81'      # Admin UI
  #    - '443:443'    # HTTPS
  #  volumes:
  #    - ./nginx/data:/data
  #    - ./nginx/letsencrypt:/etc/letsencrypt
  #  networks:
  #    - kia-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front-cliente
      - front-admin
      - backend
    networks:
      - kia-network

networks:
  kia-network:
    driver: bridge